clean:
    rm -rf build

build:
    export CMAKE_POLICY_VERSION_MINIMUM=3.5 && \
    conan install . --build=missing
    cmake --preset conan-release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    cmake --build --preset conan-release
    ln -sf build/Release/compile_commands.json .
    cp vars.cfg ./build/Release/

cbuild:
    just clean
    just build